name: Docker Image CI

on:
  push:
    branches: [ main ]

permissions:
  actions: read
  contents: read
  packages: write
  pull-requests: read


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: checkout repo
      uses: actions/checkout@v2
    - name: define commit hash
      run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: Log in to GHCR
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Configure QEMU Support
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Configure Docker Buildx
      id: docker_buildx
      uses: docker/setup-buildx-action@master
    - name: Build & Push Image
      uses: docker/build-push-action@v2.7.0
      with:
        builder: ${{ steps.docker_buildx.outputs.name }}
        platforms: linux/amd64
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.COMMIT_HASH }}, ${{ env.REGISTRY }}/${{ github.repository }}:latest
